services:
  app-dev:
    build:
      context: .
      target: dev
    container_name: spring-boot-app-dev
    volumes:
      - .:/app
    ports:
      - 8081:8081
    env_file:
      - .env.dev
    develop:
      # watch:
      #   - path: .
      #     action: sync
      #     target: /app